### ISSUE TITLE
Possible error

### ISSUE THREAD

**Issue by jpsdr** [Asd-g/AviSynth-JincResize#1]
In JincResize.cpp, line 727, is normal to have the same index ? It looks like a copy/paste mistake.
    if (args[src_left_idx + **0**].Defined())
        out_args->add(args[src_left_idx + 0], "src_left");
    if (args[src_left_idx + **1**].Defined())
        out_args->add(args[src_left_idx + 1], "src_top");
    if (args[src_left_idx + 2].Defined())
        out_args->add(args[src_left_idx + 2], "src_width");
    if (args[src_left_idx + 3].Defined())
        out_args->add(args[src_left_idx + 3], "src_height");
    if (args[src_left_idx + **0**].Defined())
        out_args->add(args[src_left_idx + 4], "quant_x");
    if (args[src_left_idx + **1**].Defined())
        out_args->add(args[src_left_idx + 5], "quant_y");

**Comment by Asd-g** [comment]
Thanks for the report.
They should be respectively 4 and 5.
Also found a bug in the AVX512 code.
Will fix later.
