### ISSUE TITLE
OpenMP compatibility

### ISSUE THREAD

**Issue by DTL2020** [Asd-g/AviSynth-JincResize#2]
I new to github and can not found way to e-mail of write private message to the main contributor to this project. It looks he not participated in this plugin discussion at forum-doom9 at https://forum.doom9.org/showthread.php?t=169813 .

I recommend to add compatibility with OpenMP - at least for main processing loops it is very easy. Just make 'dst' and 'meta' variable local for each row. Here is my code:
static void resize_plane_c(EWAPixelCoeff* coeff, const void* src_, void* VS_RESTRICT dst_,
    int dst_width, int dst_height, int src_stride, int dst_stride, float peak)
{
  //  EWAPixelCoeffMeta* meta = coeff->meta;

    const T* srcp = reinterpret_cast<const T*>(src_);
  //  T* VS_RESTRICT dstp = reinterpret_cast<T*>(dst_);

    src_stride /= sizeof(T);
    dst_stride /= sizeof(T);

#pragma omp parallel for
    for (int y = 0; y < dst_height; y++)
    {
        T* VS_RESTRICT dstp = reinterpret_cast<T*>(dst_) + y * dst_stride;

        for (int x = 0; x < dst_width; x++)
        {

            EWAPixelCoeffMeta* meta = coeff->meta + y * dst_width + x;

            const T* src_ptr = srcp + meta->start_y * static_cast<int64_t>(src_stride) + meta->start_x;
            const float* coeff_ptr = coeff->factor + meta->coeff_meta;

            float result = 0.f;

            for (int ly = 0; ly < coeff->filter_size; ly++)
            {
                for (int lx = 0; lx < coeff->filter_size; lx++)
                {
                    result += src_ptr[lx] * coeff_ptr[lx];
                }
                coeff_ptr += coeff->coeff_stride;
                src_ptr += src_stride;
            }

            if (!(std::is_same_v<T, float>))
                dstp[x] = static_cast<T>(lrintf(clamp(result, 0.f, peak)));
            else
                dstp[x] = result;

         //   meta++;
        }

      //  dstp += dst_stride;
    }
}

Same is for ASM processing. Full sources with intel C++ compiler sitring is at https://cloud.mail.ru/public/5nwM/2CBA6o3sc .

It is not as fast as using Avisynth per-frame MT but uses less memory because uses only one large coeffs table for each thread.

**Comment by Asd-g** [comment]
Can you create pull request?

**Comment by DTL2020** [comment]
I am new to github so I do not know if I will to it right but I will try. So I need to open new project at my github account and load sources and click to 'Pull-request' ? I will try with sources from version 1.2.0 a few days later.

**Comment by Asd-g** [comment]
Thanks. That way it will be visible to everyone that this part of the code comes from you.

> So I need to open new project at my github account and load sources and click to 'Pull-request' ?

> Anyone with read permissions to a repository can create a pull request, but you must have write permissions to create a branch. If you want to create a new branch for your pull request and don't have write permissions to the repository, you can fork the repository first. For more information, see "Creating a pull request from a fork" and "About forks."

Above quote is from [here](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request). Check "Creating a pull request from a fork".

**Comment by DTL2020** [comment]
It looks I sucessfully created pull request. It have additional comments in the request text. The AVX512 version was not tested because I do not have such CPU so it is good to test it if someone have. Though the changes are in pointers only and I hope it is equal to other ASM subroutines.

To compile with OpenMP it must be enabled in the VS project options or in command line for Intel C++ Compiler. Also I do not know how to link some OpenMP library with Intel C++ compiler so the compiled executable requires DLL like libiomp5md.dll to load JincResize.dll. May be it can be linked statically somehow. The build by VS2019 executable works without additional DLLs but for unknown reason very slow in compare with Intel C++ compiler build.

**Comment by Asd-g** [comment]
I tested AVX512 and it's ok.
It seems atm statically linking openmp lib is not supported for Windows - https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/optimization-and-programming-guide/openmp-support/openmp-library-support/using-the-openmp-libraries.html

**Comment by DTL2020** [comment]
So the VS2019 OpenMP builds works without additional .dlls provided
because Windows OpenMP .dll are provided with Windows system and they
are loaded from Windows system folders ?

And for Intel C++ compiled builds we need to redistribute OpenMP .dlls
provided with Intel compiler manually ? Or point users to
redistributable OpenMP libraries for Intel if available ?

**Comment by Asd-g** [comment]
> So the VS2019 OpenMP builds works without additional .dlls provided
> because Windows OpenMP .dll are provided with Windows system and they
> are loaded from Windows system folders ?

Yes, using MSVC compiler with default openmp library works without additional .dlls because openmp library (vcompxxx.lib) is provided with the other runtime files ( https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads ).

> And for Intel C++ compiled builds we need to redistribute OpenMP .dlls
> provided with Intel compiler manually ? Or point users to
> redistributable OpenMP libraries for Intel if available ?

Yes.
Here Intel redistributable packages - https://software.intel.com/content/www/us/en/develop/articles/redistributable-libraries-for-intel-c-and-fortran-2020-compilers-for-windows.html

I made a quick test (AVX2):
- Intel C++ 19.1 with it omp library - 180.85 fps (mean);
- clang-cl 11.0.0 with it omp library - 169.5 fps (mean);
- MSVC 19.27.29115 with it omp library - 211.95 fps (mean).

Also Intel C++ only for AVX2 (any bit depth) gives a slightly different result than MSVC/clang-cl. MSVC and clang-cl have identical results.
