### ISSUE TITLE
'blur' not working in JincResize()

### ISSUE THREAD

**Issue by Dogway** [Asd-g/AviSynth-JincResize#9]
Was trying to match some EWA presets by N. Rubidoux but the blur parameter doesn't seem to work.
```
RGB/YUV and 8-bit/HBD
JincResize(width()*2,height()*2,tap=3,blur=0.9812505644269356)
```

**Comment by Asd-g** [comment]
Try with 1.874943557.

The current blur is `blur = 1.0 - blur / 100.0;`

**Comment by Dogway** [comment]
Thanks! That worked, testing it out 1.70 seemed to match better to avs_libplacebo but that might be due to rounding errors.

EDIT: Looks like some modes overflow the max permitted. EWASharpest is 11.45 (0.8855), while EWASoft is -1.5 (1.015)
